sudo: false
language: ruby
cache: bundler
rvm:
- 2.6.6
install:
- bundle install
before_script:
- git config --global user.email "yuseong12345@naver.com"
- git config --global user.name "SEONGJAE-YOO"
script: bundle exec rake site:deploy --quiet
env:
  global:
   - secure: "voQonCY6RYJzGqmn/hd+r8h1/LgrxWGqkVUMSB5Cj9YjrRDj2P18QA9JXHj869c1crZTEWIaDhPSC536ZlhJnn2u1QDV8PX2MzADGqic9lwt4PkqldreWnQ+JvH6CszMQmXhq0ZE1y9Zi00Gpaaaw6CtvrfFALUKSFps+KDVzF92UG3xSdo8Gjg0xdcCHclgzG5RJ6JT6UzY4hM/8wt8yUbV4zzBSuNPZsqDsVmPxaottfJurJK4SfFaRRPw5Tq5UqThBTp79SOGw/cdHZClL93xsnKLa7XoAHsF2lxnvNd6DfDWN0jZKoQGo6yYPiAkck0i3IEAoui8xCidfs1Hg4f5LC2KLi64yFxXX1O5l+jFdbuP1L3R9ff3UR4a7ynJMYwBPxClkMoq4PRhPrf2OIUHlhEhAhX0c+xvAEq32tBXT73ovjItJVbIUpudTQuvvTQsXbNw8txtX0StIJx4eOH1pwdv09huT5Hz72rIzWOikSp5AeKNpIbHDN5p7zKjrJe5wXBFTZo4ot36fka8rDBebNcxFw2G7d1fijZZ9ZCyasRjHt9pNj4XCmCKqGjge/FG1wpGd6qko9hgukX1TBruoefEEO2B7EvvBgYMGzDILZp+egkQkscYPWxH/XGz5gEktQ9+2r3yroSZf+N3arwMAsC799l34K18YAfwCX8="
branches:
  only:
  - master
